export const products = [
  {
    id: 1,
    image: "images/hydrating-mousse.png",
    name: "Увлажняющий мусс",
    purpose: "для нормальной кожи",
    description: "Глубоко увлажняют кожу лица, оставляя её мягкой и гладкой.",
    ingredients: [
      "активные натуральные комплексы",
      "витамины С, А, РР, В И Е",
      "солнцезащитные компоненты",
    ],
    price: 2750,
    currency: "₽",
  },
  {
    id: 2,
    image: "images/moisturizing-mask.png",
    name: "Увлажняющая маска",
    purpose: "для нормальной кожи",
    description: "Способствует удерживанию влаги в верхних слоях кожи.",
    ingredients: ["воски", "минералы", "масла"],
    price: 3500,
    currency: "₽",
  },
  {
    id: 3,
    image: "images/cleansing-gel.png",
    name: "Гель для умывания",
    purpose: "для нормальной кожи",
    description: "Интенсивно очищает, не повреждает защитный барьер кожи.",
    ingredients: [
      "минералы",
      "витамины С, А, РР, В И Е",
      "солнцезащитные компоненты",
    ],
    price: 1650,
    currency: "₽",
  },
  {
    id: 4,
    image: "images/gift-set-1.png",
    name: "Подарочный набор №1",
    purpose: "для нормальной кожи",
    description: "Набор, состоящий из увлажняющего крема и маски.",
    ingredients: ["воски", "минералы", "масла"],
    price: 3250,
    currency: "₽",
  },
  {
    id: 5,
    image: "images/gift-set-5.png",
    name: "Подарочный набор №5",
    purpose: "для нормальной кожи",
    description:
      "Весь набор средств Invisible symphony, крем, маска, мусс и гель для умывания.",
    ingredients: ["воски", "минералы", "масла"],
    price: 7520,
    currency: "₽",
  },
];
